/*
 * generated by Xtext
 */
package net.certware.sacm.dsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractSacmDslValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://schema.omg.org/SACM/1.0"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://schema.omg.org/SACM/1.0/Argumentation"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://schema.omg.org/SACM/1.0/Evidence"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.eclipse.org/emf/2002/Ecore"));
		return result;
	}
}
