/**
 * Copyright (c) 2013 United States Government as represented by the Administrator for The National Aeronautics and Space Administration.  All Rights Reserved.
 * 
 */
package net.certware.sacm.SACM.Evidence.provider;

import java.util.ArrayList;
import java.util.Collection;

import net.certware.sacm.SACM.Evidence.util.EvidenceAdapterFactory;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemColorProvider;
import org.eclipse.emf.edit.provider.IItemFontProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class EvidenceItemProviderAdapterFactory extends EvidenceAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static final String copyright = "Copyright (c) 2013 United States Government as represented by the Administrator for The National Aeronautics and Space Administration.  All Rights Reserved.\n"; //$NON-NLS-1$

	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public EvidenceItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
		supportedTypes.add(IItemColorProvider.class);
		supportedTypes.add(IItemFontProvider.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.Consistency} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConsistencyItemProvider consistencyItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.Consistency}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConsistencyAdapter() {
		if (consistencyItemProvider == null) {
			consistencyItemProvider = new ConsistencyItemProvider(this);
		}

		return consistencyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.Completeness} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CompletenessItemProvider completenessItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.Completeness}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCompletenessAdapter() {
		if (completenessItemProvider == null) {
			completenessItemProvider = new CompletenessItemProvider(this);
		}

		return completenessItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.Document} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DocumentItemProvider documentItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.Document}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDocumentAdapter() {
		if (documentItemProvider == null) {
			documentItemProvider = new DocumentItemProvider(this);
		}

		return documentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.Confidence} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConfidenceItemProvider confidenceItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.Confidence}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConfidenceAdapter() {
		if (confidenceItemProvider == null) {
			confidenceItemProvider = new ConfidenceItemProvider(this);
		}

		return confidenceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.ApprovedBy} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ApprovedByItemProvider approvedByItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.ApprovedBy}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createApprovedByAdapter() {
		if (approvedByItemProvider == null) {
			approvedByItemProvider = new ApprovedByItemProvider(this);
		}

		return approvedByItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.CreatedBy} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CreatedByItemProvider createdByItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.CreatedBy}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCreatedByAdapter() {
		if (createdByItemProvider == null) {
			createdByItemProvider = new CreatedByItemProvider(this);
		}

		return createdByItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.Tool} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ToolItemProvider toolItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.Tool}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createToolAdapter() {
		if (toolItemProvider == null) {
			toolItemProvider = new ToolItemProvider(this);
		}

		return toolItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.Method} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MethodItemProvider methodItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.Method}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMethodAdapter() {
		if (methodItemProvider == null) {
			methodItemProvider = new MethodItemProvider(this);
		}

		return methodItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.IsBasedOn} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IsBasedOnItemProvider isBasedOnItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.IsBasedOn}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIsBasedOnAdapter() {
		if (isBasedOnItemProvider == null) {
			isBasedOnItemProvider = new IsBasedOnItemProvider(this);
		}

		return isBasedOnItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.IsA} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IsAItemProvider isAItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.IsA}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIsAAdapter() {
		if (isAItemProvider == null) {
			isAItemProvider = new IsAItemProvider(this);
		}

		return isAItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.IsCharacterizedBy} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IsCharacterizedByItemProvider isCharacterizedByItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.IsCharacterizedBy}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIsCharacterizedByAdapter() {
		if (isCharacterizedByItemProvider == null) {
			isCharacterizedByItemProvider = new IsCharacterizedByItemProvider(this);
		}

		return isCharacterizedByItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.Person} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PersonItemProvider personItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.Person}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPersonAdapter() {
		if (personItemProvider == null) {
			personItemProvider = new PersonItemProvider(this);
		}

		return personItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.Organization} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OrganizationItemProvider organizationItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.Organization}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOrganizationAdapter() {
		if (organizationItemProvider == null) {
			organizationItemProvider = new OrganizationItemProvider(this);
		}

		return organizationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.EvidenceContainer} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EvidenceContainerItemProvider evidenceContainerItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.EvidenceContainer}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEvidenceContainerAdapter() {
		if (evidenceContainerItemProvider == null) {
			evidenceContainerItemProvider = new EvidenceContainerItemProvider(this);
		}

		return evidenceContainerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.EndTime} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EndTimeItemProvider endTimeItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.EndTime}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEndTimeAdapter() {
		if (endTimeItemProvider == null) {
			endTimeItemProvider = new EndTimeItemProvider(this);
		}

		return endTimeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.Assertion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AssertionItemProvider assertionItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.Assertion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAssertionAdapter() {
		if (assertionItemProvider == null) {
			assertionItemProvider = new AssertionItemProvider(this);
		}

		return assertionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.Object} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ObjectItemProvider objectItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.Object}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createObjectAdapter() {
		if (objectItemProvider == null) {
			objectItemProvider = new ObjectItemProvider(this);
		}

		return objectItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.CompositeObject} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CompositeObjectItemProvider compositeObjectItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.CompositeObject}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCompositeObjectAdapter() {
		if (compositeObjectItemProvider == null) {
			compositeObjectItemProvider = new CompositeObjectItemProvider(this);
		}

		return compositeObjectItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.RoleBinding} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RoleBindingItemProvider roleBindingItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.RoleBinding}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRoleBindingAdapter() {
		if (roleBindingItemProvider == null) {
			roleBindingItemProvider = new RoleBindingItemProvider(this);
		}

		return roleBindingItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.StartTime} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StartTimeItemProvider startTimeItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.StartTime}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStartTimeAdapter() {
		if (startTimeItemProvider == null) {
			startTimeItemProvider = new StartTimeItemProvider(this);
		}

		return startTimeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.Relevance} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RelevanceItemProvider relevanceItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.Relevance}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRelevanceAdapter() {
		if (relevanceItemProvider == null) {
			relevanceItemProvider = new RelevanceItemProvider(this);
		}

		return relevanceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.Significance} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SignificanceItemProvider significanceItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.Significance}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSignificanceAdapter() {
		if (significanceItemProvider == null) {
			significanceItemProvider = new SignificanceItemProvider(this);
		}

		return significanceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.Accuracy} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AccuracyItemProvider accuracyItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.Accuracy}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAccuracyAdapter() {
		if (accuracyItemProvider == null) {
			accuracyItemProvider = new AccuracyItemProvider(this);
		}

		return accuracyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.HasRoleIn} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected HasRoleInItemProvider hasRoleInItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.HasRoleIn}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createHasRoleInAdapter() {
		if (hasRoleInItemProvider == null) {
			hasRoleInItemProvider = new HasRoleInItemProvider(this);
		}

		return hasRoleInItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.IsScopedBy} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IsScopedByItemProvider isScopedByItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.IsScopedBy}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIsScopedByAdapter() {
		if (isScopedByItemProvider == null) {
			isScopedByItemProvider = new IsScopedByItemProvider(this);
		}

		return isScopedByItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.AtTime} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AtTimeItemProvider atTimeItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.AtTime}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAtTimeAdapter() {
		if (atTimeItemProvider == null) {
			atTimeItemProvider = new AtTimeItemProvider(this);
		}

		return atTimeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.Originality} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OriginalityItemProvider originalityItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.Originality}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOriginalityAdapter() {
		if (originalityItemProvider == null) {
			originalityItemProvider = new OriginalityItemProvider(this);
		}

		return originalityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.Reporting} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReportingItemProvider reportingItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.Reporting}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReportingAdapter() {
		if (reportingItemProvider == null) {
			reportingItemProvider = new ReportingItemProvider(this);
		}

		return reportingItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.Reliability} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReliabilityItemProvider reliabilityItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.Reliability}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReliabilityAdapter() {
		if (reliabilityItemProvider == null) {
			reliabilityItemProvider = new ReliabilityItemProvider(this);
		}

		return reliabilityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.Supports} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SupportsItemProvider supportsItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.Supports}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSupportsAdapter() {
		if (supportsItemProvider == null) {
			supportsItemProvider = new SupportsItemProvider(this);
		}

		return supportsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.IsGeneratedAt} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IsGeneratedAtItemProvider isGeneratedAtItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.IsGeneratedAt}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIsGeneratedAtAdapter() {
		if (isGeneratedAtItemProvider == null) {
			isGeneratedAtItemProvider = new IsGeneratedAtItemProvider(this);
		}

		return isGeneratedAtItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.Support} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SupportItemProvider supportItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.Support}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSupportAdapter() {
		if (supportItemProvider == null) {
			supportItemProvider = new SupportItemProvider(this);
		}

		return supportItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.Conflicts} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConflictsItemProvider conflictsItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.Conflicts}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConflictsAdapter() {
		if (conflictsItemProvider == null) {
			conflictsItemProvider = new ConflictsItemProvider(this);
		}

		return conflictsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.Refutes} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RefutesItemProvider refutesItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.Refutes}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRefutesAdapter() {
		if (refutesItemProvider == null) {
			refutesItemProvider = new RefutesItemProvider(this);
		}

		return refutesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.Negates} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NegatesItemProvider negatesItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.Negates}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNegatesAdapter() {
		if (negatesItemProvider == null) {
			negatesItemProvider = new NegatesItemProvider(this);
		}

		return negatesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.UnknownObject} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UnknownObjectItemProvider unknownObjectItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.UnknownObject}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUnknownObjectAdapter() {
		if (unknownObjectItemProvider == null) {
			unknownObjectItemProvider = new UnknownObjectItemProvider(this);
		}

		return unknownObjectItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.Resolves} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ResolvesItemProvider resolvesItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.Resolves}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createResolvesAdapter() {
		if (resolvesItemProvider == null) {
			resolvesItemProvider = new ResolvesItemProvider(this);
		}

		return resolvesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.EvidenceRequest} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EvidenceRequestItemProvider evidenceRequestItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.EvidenceRequest}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEvidenceRequestAdapter() {
		if (evidenceRequestItemProvider == null) {
			evidenceRequestItemProvider = new EvidenceRequestItemProvider(this);
		}

		return evidenceRequestItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.ProjectObjective} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ProjectObjectiveItemProvider projectObjectiveItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.ProjectObjective}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createProjectObjectiveAdapter() {
		if (projectObjectiveItemProvider == null) {
			projectObjectiveItemProvider = new ProjectObjectiveItemProvider(this);
		}

		return projectObjectiveItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.Activity} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ActivityItemProvider activityItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.Activity}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createActivityAdapter() {
		if (activityItemProvider == null) {
			activityItemProvider = new ActivityItemProvider(this);
		}

		return activityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.DependsOn} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DependsOnItemProvider dependsOnItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.DependsOn}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDependsOnAdapter() {
		if (dependsOnItemProvider == null) {
			dependsOnItemProvider = new DependsOnItemProvider(this);
		}

		return dependsOnItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.Satisfies} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SatisfiesItemProvider satisfiesItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.Satisfies}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSatisfiesAdapter() {
		if (satisfiesItemProvider == null) {
			satisfiesItemProvider = new SatisfiesItemProvider(this);
		}

		return satisfiesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.ReferencedClaim} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReferencedClaimItemProvider referencedClaimItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.ReferencedClaim}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReferencedClaimAdapter() {
		if (referencedClaimItemProvider == null) {
			referencedClaimItemProvider = new ReferencedClaimItemProvider(this);
		}

		return referencedClaimItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.Weakens} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WeakensItemProvider weakensItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.Weakens}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createWeakensAdapter() {
		if (weakensItemProvider == null) {
			weakensItemProvider = new WeakensItemProvider(this);
		}

		return weakensItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.Amplifies} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AmplifiesItemProvider amplifiesItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.Amplifies}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAmplifiesAdapter() {
		if (amplifiesItemProvider == null) {
			amplifiesItemProvider = new AmplifiesItemProvider(this);
		}

		return amplifiesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.Challenges} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ChallengesItemProvider challengesItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.Challenges}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createChallengesAdapter() {
		if (challengesItemProvider == null) {
			challengesItemProvider = new ChallengesItemProvider(this);
		}

		return challengesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.Strength} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StrengthItemProvider strengthItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.Strength}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStrengthAdapter() {
		if (strengthItemProvider == null) {
			strengthItemProvider = new StrengthItemProvider(this);
		}

		return strengthItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.IsAcquiredAt} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IsAcquiredAtItemProvider isAcquiredAtItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.IsAcquiredAt}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIsAcquiredAtAdapter() {
		if (isAcquiredAtItemProvider == null) {
			isAcquiredAtItemProvider = new IsAcquiredAtItemProvider(this);
		}

		return isAcquiredAtItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.IsTransferredTo} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IsTransferredToItemProvider isTransferredToItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.IsTransferredTo}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIsTransferredToAdapter() {
		if (isTransferredToItemProvider == null) {
			isTransferredToItemProvider = new IsTransferredToItemProvider(this);
		}

		return isTransferredToItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.OwnedBy} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OwnedByItemProvider ownedByItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.OwnedBy}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOwnedByAdapter() {
		if (ownedByItemProvider == null) {
			ownedByItemProvider = new OwnedByItemProvider(this);
		}

		return ownedByItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.IsPartOf} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IsPartOfItemProvider isPartOfItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.IsPartOf}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIsPartOfAdapter() {
		if (isPartOfItemProvider == null) {
			isPartOfItemProvider = new IsPartOfItemProvider(this);
		}

		return isPartOfItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.IsRevokedAt} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IsRevokedAtItemProvider isRevokedAtItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.IsRevokedAt}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIsRevokedAtAdapter() {
		if (isRevokedAtItemProvider == null) {
			isRevokedAtItemProvider = new IsRevokedAtItemProvider(this);
		}

		return isRevokedAtItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.ProvidesContext} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ProvidesContextItemProvider providesContextItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.ProvidesContext}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createProvidesContextAdapter() {
		if (providesContextItemProvider == null) {
			providesContextItemProvider = new ProvidesContextItemProvider(this);
		}

		return providesContextItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.MeansThat} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MeansThatItemProvider meansThatItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.MeansThat}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMeansThatAdapter() {
		if (meansThatItemProvider == null) {
			meansThatItemProvider = new MeansThatItemProvider(this);
		}

		return meansThatItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.CareOf} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CareOfItemProvider careOfItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.CareOf}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCareOfAdapter() {
		if (careOfItemProvider == null) {
			careOfItemProvider = new CareOfItemProvider(this);
		}

		return careOfItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.AtLocation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AtLocationItemProvider atLocationItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.AtLocation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAtLocationAdapter() {
		if (atLocationItemProvider == null) {
			atLocationItemProvider = new AtLocationItemProvider(this);
		}

		return atLocationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.IsCreatedAt} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IsCreatedAtItemProvider isCreatedAtItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.IsCreatedAt}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIsCreatedAtAdapter() {
		if (isCreatedAtItemProvider == null) {
			isCreatedAtItemProvider = new IsCreatedAtItemProvider(this);
		}

		return isCreatedAtItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.RequiresContainer} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RequiresContainerItemProvider requiresContainerItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.RequiresContainer}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRequiresContainerAdapter() {
		if (requiresContainerItemProvider == null) {
			requiresContainerItemProvider = new RequiresContainerItemProvider(this);
		}

		return requiresContainerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.Service} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ServiceItemProvider serviceItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.Service}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createServiceAdapter() {
		if (serviceItemProvider == null) {
			serviceItemProvider = new ServiceItemProvider(this);
		}

		return serviceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.HasElectronicSource} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected HasElectronicSourceItemProvider hasElectronicSourceItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.HasElectronicSource}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createHasElectronicSourceAdapter() {
		if (hasElectronicSourceItemProvider == null) {
			hasElectronicSourceItemProvider = new HasElectronicSourceItemProvider(this);
		}

		return hasElectronicSourceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.IsExpressedInLanguage} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IsExpressedInLanguageItemProvider isExpressedInLanguageItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.IsExpressedInLanguage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIsExpressedInLanguageAdapter() {
		if (isExpressedInLanguageItemProvider == null) {
			isExpressedInLanguageItemProvider = new IsExpressedInLanguageItemProvider(this);
		}

		return isExpressedInLanguageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.UsingProcess} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UsingProcessItemProvider usingProcessItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.UsingProcess}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUsingProcessAdapter() {
		if (usingProcessItemProvider == null) {
			usingProcessItemProvider = new UsingProcessItemProvider(this);
		}

		return usingProcessItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.HasSecurityClassification} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected HasSecurityClassificationItemProvider hasSecurityClassificationItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.HasSecurityClassification}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createHasSecurityClassificationAdapter() {
		if (hasSecurityClassificationItemProvider == null) {
			hasSecurityClassificationItemProvider = new HasSecurityClassificationItemProvider(this);
		}

		return hasSecurityClassificationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.IsReleaseableTo} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IsReleaseableToItemProvider isReleaseableToItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.IsReleaseableTo}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIsReleaseableToAdapter() {
		if (isReleaseableToItemProvider == null) {
			isReleaseableToItemProvider = new IsReleaseableToItemProvider(this);
		}

		return isReleaseableToItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.EvidenceGroup} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EvidenceGroupItemProvider evidenceGroupItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.EvidenceGroup}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEvidenceGroupAdapter() {
		if (evidenceGroupItemProvider == null) {
			evidenceGroupItemProvider = new EvidenceGroupItemProvider(this);
		}

		return evidenceGroupItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.HasVersion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected HasVersionItemProvider hasVersionItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.HasVersion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createHasVersionAdapter() {
		if (hasVersionItemProvider == null) {
			hasVersionItemProvider = new HasVersionItemProvider(this);
		}

		return hasVersionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.HasMedia} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected HasMediaItemProvider hasMediaItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.HasMedia}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createHasMediaAdapter() {
		if (hasMediaItemProvider == null) {
			hasMediaItemProvider = new HasMediaItemProvider(this);
		}

		return hasMediaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.Exhibit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExhibitItemProvider exhibitItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.Exhibit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExhibitAdapter() {
		if (exhibitItemProvider == null) {
			exhibitItemProvider = new ExhibitItemProvider(this);
		}

		return exhibitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.ExtendedEvidenceAttribute} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExtendedEvidenceAttributeItemProvider extendedEvidenceAttributeItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.ExtendedEvidenceAttribute}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExtendedEvidenceAttributeAdapter() {
		if (extendedEvidenceAttributeItemProvider == null) {
			extendedEvidenceAttributeItemProvider = new ExtendedEvidenceAttributeItemProvider(this);
		}

		return extendedEvidenceAttributeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.ExtendedDocumentProperty} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExtendedDocumentPropertyItemProvider extendedDocumentPropertyItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.ExtendedDocumentProperty}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExtendedDocumentPropertyAdapter() {
		if (extendedDocumentPropertyItemProvider == null) {
			extendedDocumentPropertyItemProvider = new ExtendedDocumentPropertyItemProvider(this);
		}

		return extendedDocumentPropertyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.Record} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RecordItemProvider recordItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.Record}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRecordAdapter() {
		if (recordItemProvider == null) {
			recordItemProvider = new RecordItemProvider(this);
		}

		return recordItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.ObjectifiedAssertion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ObjectifiedAssertionItemProvider objectifiedAssertionItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.ObjectifiedAssertion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createObjectifiedAssertionAdapter() {
		if (objectifiedAssertionItemProvider == null) {
			objectifiedAssertionItemProvider = new ObjectifiedAssertionItemProvider(this);
		}

		return objectifiedAssertionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.IsModifiedBy} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IsModifiedByItemProvider isModifiedByItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.IsModifiedBy}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIsModifiedByAdapter() {
		if (isModifiedByItemProvider == null) {
			isModifiedByItemProvider = new IsModifiedByItemProvider(this);
		}

		return isModifiedByItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.PerformedBy} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PerformedByItemProvider performedByItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.PerformedBy}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPerformedByAdapter() {
		if (performedByItemProvider == null) {
			performedByItemProvider = new PerformedByItemProvider(this);
		}

		return performedByItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.ContainerConsistency} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ContainerConsistencyItemProvider containerConsistencyItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.ContainerConsistency}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createContainerConsistencyAdapter() {
		if (containerConsistencyItemProvider == null) {
			containerConsistencyItemProvider = new ContainerConsistencyItemProvider(this);
		}

		return containerConsistencyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.ContainerCompleteness} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ContainerCompletenessItemProvider containerCompletenessItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.ContainerCompleteness}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createContainerCompletenessAdapter() {
		if (containerCompletenessItemProvider == null) {
			containerCompletenessItemProvider = new ContainerCompletenessItemProvider(this);
		}

		return containerCompletenessItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.CompliesTo} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CompliesToItemProvider compliesToItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.CompliesTo}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCompliesToAdapter() {
		if (compliesToItemProvider == null) {
			compliesToItemProvider = new CompliesToItemProvider(this);
		}

		return compliesToItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.sacm.SACM.Evidence.ExtendedProjectProperty} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExtendedProjectPropertyItemProvider extendedProjectPropertyItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.sacm.SACM.Evidence.ExtendedProjectProperty}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExtendedProjectPropertyAdapter() {
		if (extendedProjectPropertyItemProvider == null) {
			extendedProjectPropertyItemProvider = new ExtendedProjectPropertyItemProvider(this);
		}

		return extendedProjectPropertyItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (consistencyItemProvider != null) consistencyItemProvider.dispose();
		if (completenessItemProvider != null) completenessItemProvider.dispose();
		if (documentItemProvider != null) documentItemProvider.dispose();
		if (confidenceItemProvider != null) confidenceItemProvider.dispose();
		if (approvedByItemProvider != null) approvedByItemProvider.dispose();
		if (createdByItemProvider != null) createdByItemProvider.dispose();
		if (toolItemProvider != null) toolItemProvider.dispose();
		if (methodItemProvider != null) methodItemProvider.dispose();
		if (isBasedOnItemProvider != null) isBasedOnItemProvider.dispose();
		if (isAItemProvider != null) isAItemProvider.dispose();
		if (isCharacterizedByItemProvider != null) isCharacterizedByItemProvider.dispose();
		if (personItemProvider != null) personItemProvider.dispose();
		if (organizationItemProvider != null) organizationItemProvider.dispose();
		if (evidenceContainerItemProvider != null) evidenceContainerItemProvider.dispose();
		if (endTimeItemProvider != null) endTimeItemProvider.dispose();
		if (assertionItemProvider != null) assertionItemProvider.dispose();
		if (objectItemProvider != null) objectItemProvider.dispose();
		if (compositeObjectItemProvider != null) compositeObjectItemProvider.dispose();
		if (roleBindingItemProvider != null) roleBindingItemProvider.dispose();
		if (startTimeItemProvider != null) startTimeItemProvider.dispose();
		if (relevanceItemProvider != null) relevanceItemProvider.dispose();
		if (significanceItemProvider != null) significanceItemProvider.dispose();
		if (accuracyItemProvider != null) accuracyItemProvider.dispose();
		if (hasRoleInItemProvider != null) hasRoleInItemProvider.dispose();
		if (isScopedByItemProvider != null) isScopedByItemProvider.dispose();
		if (atTimeItemProvider != null) atTimeItemProvider.dispose();
		if (originalityItemProvider != null) originalityItemProvider.dispose();
		if (reportingItemProvider != null) reportingItemProvider.dispose();
		if (reliabilityItemProvider != null) reliabilityItemProvider.dispose();
		if (supportsItemProvider != null) supportsItemProvider.dispose();
		if (isGeneratedAtItemProvider != null) isGeneratedAtItemProvider.dispose();
		if (supportItemProvider != null) supportItemProvider.dispose();
		if (conflictsItemProvider != null) conflictsItemProvider.dispose();
		if (refutesItemProvider != null) refutesItemProvider.dispose();
		if (negatesItemProvider != null) negatesItemProvider.dispose();
		if (unknownObjectItemProvider != null) unknownObjectItemProvider.dispose();
		if (resolvesItemProvider != null) resolvesItemProvider.dispose();
		if (evidenceRequestItemProvider != null) evidenceRequestItemProvider.dispose();
		if (projectObjectiveItemProvider != null) projectObjectiveItemProvider.dispose();
		if (activityItemProvider != null) activityItemProvider.dispose();
		if (dependsOnItemProvider != null) dependsOnItemProvider.dispose();
		if (satisfiesItemProvider != null) satisfiesItemProvider.dispose();
		if (referencedClaimItemProvider != null) referencedClaimItemProvider.dispose();
		if (weakensItemProvider != null) weakensItemProvider.dispose();
		if (amplifiesItemProvider != null) amplifiesItemProvider.dispose();
		if (challengesItemProvider != null) challengesItemProvider.dispose();
		if (strengthItemProvider != null) strengthItemProvider.dispose();
		if (isAcquiredAtItemProvider != null) isAcquiredAtItemProvider.dispose();
		if (isTransferredToItemProvider != null) isTransferredToItemProvider.dispose();
		if (ownedByItemProvider != null) ownedByItemProvider.dispose();
		if (isPartOfItemProvider != null) isPartOfItemProvider.dispose();
		if (isRevokedAtItemProvider != null) isRevokedAtItemProvider.dispose();
		if (providesContextItemProvider != null) providesContextItemProvider.dispose();
		if (meansThatItemProvider != null) meansThatItemProvider.dispose();
		if (careOfItemProvider != null) careOfItemProvider.dispose();
		if (atLocationItemProvider != null) atLocationItemProvider.dispose();
		if (isCreatedAtItemProvider != null) isCreatedAtItemProvider.dispose();
		if (requiresContainerItemProvider != null) requiresContainerItemProvider.dispose();
		if (serviceItemProvider != null) serviceItemProvider.dispose();
		if (hasElectronicSourceItemProvider != null) hasElectronicSourceItemProvider.dispose();
		if (isExpressedInLanguageItemProvider != null) isExpressedInLanguageItemProvider.dispose();
		if (usingProcessItemProvider != null) usingProcessItemProvider.dispose();
		if (hasSecurityClassificationItemProvider != null) hasSecurityClassificationItemProvider.dispose();
		if (isReleaseableToItemProvider != null) isReleaseableToItemProvider.dispose();
		if (evidenceGroupItemProvider != null) evidenceGroupItemProvider.dispose();
		if (hasVersionItemProvider != null) hasVersionItemProvider.dispose();
		if (hasMediaItemProvider != null) hasMediaItemProvider.dispose();
		if (exhibitItemProvider != null) exhibitItemProvider.dispose();
		if (extendedEvidenceAttributeItemProvider != null) extendedEvidenceAttributeItemProvider.dispose();
		if (extendedDocumentPropertyItemProvider != null) extendedDocumentPropertyItemProvider.dispose();
		if (recordItemProvider != null) recordItemProvider.dispose();
		if (objectifiedAssertionItemProvider != null) objectifiedAssertionItemProvider.dispose();
		if (isModifiedByItemProvider != null) isModifiedByItemProvider.dispose();
		if (performedByItemProvider != null) performedByItemProvider.dispose();
		if (containerConsistencyItemProvider != null) containerConsistencyItemProvider.dispose();
		if (containerCompletenessItemProvider != null) containerCompletenessItemProvider.dispose();
		if (compliesToItemProvider != null) compliesToItemProvider.dispose();
		if (extendedProjectPropertyItemProvider != null) extendedProjectPropertyItemProvider.dispose();
	}

}
