/*
* generated by Xtext
*/
package net.certware.state.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import net.certware.state.services.StateAnalysisGrammarAccess;

public class StateAnalysisParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private StateAnalysisGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected net.certware.state.parser.antlr.internal.InternalStateAnalysisParser createParser(XtextTokenStream stream) {
		return new net.certware.state.parser.antlr.internal.InternalStateAnalysisParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "System";
	}
	
	public StateAnalysisGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(StateAnalysisGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
