/*
* generated by Xtext
*/
package net.certware.argument.sfp.ui.contentassist;

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class SemiFormalProofProposalProvider extends AbstractSemiFormalProofProposalProvider {

}
