/**
 * NOT generated by Xtext
 */
package net.certware.hazard.stpa.ui.labeling;

import com.google.inject.Inject;
import net.certware.hazard.stpa.hazardAnalysis.Accident;
import net.certware.hazard.stpa.hazardAnalysis.Constraint;
import net.certware.hazard.stpa.hazardAnalysis.Control;
import net.certware.hazard.stpa.hazardAnalysis.Design;
import net.certware.hazard.stpa.hazardAnalysis.Hazard;
import net.certware.hazard.stpa.hazardAnalysis.HazardAccidentLikelihood;
import net.certware.hazard.stpa.hazardAnalysis.HazardExposure;
import net.certware.hazard.stpa.hazardAnalysis.HazardLevel;
import net.certware.hazard.stpa.hazardAnalysis.HazardLikelihood;
import net.certware.hazard.stpa.hazardAnalysis.HazardSeverity;
import net.certware.hazard.stpa.hazardAnalysis.Incident;
import net.certware.hazard.stpa.hazardAnalysis.Model;
import net.certware.hazard.stpa.hazardAnalysis.Note;
import net.certware.hazard.stpa.hazardAnalysis.Requirement;
import net.certware.hazard.stpa.hazardAnalysis.RiskLevel;
import net.certware.hazard.stpa.hazardAnalysis.Scenario;
import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

/**
 * Provides labels for a EObjects.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#labelProvider
 */
@SuppressWarnings("all")
public class HazardAnalysisLabelProvider extends DefaultEObjectLabelProvider {
  @Inject
  public HazardAnalysisLabelProvider(final AdapterFactoryLabelProvider delegate) {
    super(delegate);
  }
  
  public String image(final Model m) {
    return "obj16/model.gif";
  }
  
  public String image(final Accident a) {
    return "obj16/accident.gif";
  }
  
  public String image(final Incident i) {
    return "obj16/incident.gif";
  }
  
  public String image(final Hazard h) {
    return "obj16/hazard.gif";
  }
  
  public String image(final RiskLevel r) {
    return "obj16/risklevel.gif";
  }
  
  public String image(final HazardLevel h) {
    return "obj16/hazardlevel.gif";
  }
  
  public String image(final HazardExposure h) {
    return "obj16/hazardexposure.gif";
  }
  
  public String image(final HazardAccidentLikelihood h) {
    return "obj16/hazardaccidentlikelihood.gif";
  }
  
  public String image(final HazardSeverity h) {
    return "obj16/hazardseverity.gif";
  }
  
  public String image(final HazardLikelihood h) {
    return "obj16/hazardlikelihood.gif";
  }
  
  public String image(final Constraint c) {
    return "obj16/constraint.gif";
  }
  
  public String image(final Requirement r) {
    return "obj16/requirement.gif";
  }
  
  public String image(final Design d) {
    return "obj16/design.gif";
  }
  
  public String image(final Scenario s) {
    return "obj16/scenario.gif";
  }
  
  public String image(final Control c) {
    return "obj16/control.gif";
  }
  
  public String image(final Note n) {
    return "obj16/note.gif";
  }
  
  /**
   * text reponses
   */
  public String text(final Model e) {
    return "Model";
  }
  
  public String text(final Accident e) {
    String _ranking = e.getRanking();
    String _plus = (("Accident" + " ") + _ranking);
    return _plus;
  }
  
  public String text(final Incident e) {
    String _ranking = e.getRanking();
    String _plus = (("Incident" + " ") + _ranking);
    return _plus;
  }
  
  public String text(final Hazard e) {
    return "Hazard";
  }
  
  public String text(final RiskLevel e) {
    return "Risk Level";
  }
  
  public String text(final HazardLevel e) {
    return "Hazard Level";
  }
  
  public String text(final HazardExposure e) {
    String _exposure = e.getExposure();
    String _plus = (("Exposure" + " ") + _exposure);
    return _plus;
  }
  
  public String text(final HazardAccidentLikelihood e) {
    String _likelihood = e.getLikelihood();
    String _plus = (("Accident Likelihood" + " ") + _likelihood);
    return _plus;
  }
  
  public String text(final HazardSeverity e) {
    String _value = e.getValue();
    String _plus = (("Hazard Severity" + " ") + _value);
    return _plus;
  }
  
  public String text(final HazardLikelihood e) {
    String _value = e.getValue();
    String _plus = (("Hazard Likelihood" + " ") + _value);
    return _plus;
  }
  
  public String text(final Constraint e) {
    String _constraint = e.getConstraint();
    String _plus = (("Constraint" + " ") + _constraint);
    return _plus;
  }
  
  public String text(final Requirement e) {
    String _requirement = e.getRequirement();
    String _plus = (("Requirement" + " ") + _requirement);
    return _plus;
  }
  
  public String text(final Design e) {
    String _allocation = e.getAllocation();
    String _plus = (("Design" + " ") + _allocation);
    return _plus;
  }
  
  public String text(final Scenario e) {
    String _scenario = e.getScenario();
    String _plus = (("Scenario" + " ") + _scenario);
    return _plus;
  }
  
  public String text(final Control e) {
    String _control = e.getControl();
    String _plus = (("Control" + " ") + _control);
    return _plus;
  }
  
  public String text(final Note e) {
    String _note = e.getNote();
    String _plus = (("Note" + " ") + _note);
    return _plus;
  }
}
