/**
 * generated by Xtext
 */
package net.certware.evidence.hugin.serializer;

import net.certware.evidence.hugin.serializer.AbstractNetDSLSemanticSequencer;

@SuppressWarnings("all")
public class NetDSLSemanticSequencer extends AbstractNetDSLSemanticSequencer {
}
