/**
 * generated by Xtext
 */
package net.certware.intent.state.validation;


/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class StateSpecificationValidator extends AbstractStateSpecificationValidator {
}
