/**
 * Copyright (c) 2011 Object Management Group (SAEM metamodel)
 * Copyright (c) 2010-2011 United States Government as represented by the Administrator for The National Aeronautics and Space Administration.  All Rights Reserved.  (generated models) 
 */

package net.certware.evidence.evidence.provider;

import java.util.ArrayList;
import java.util.Collection;

import net.certware.evidence.evidence.util.EvidenceAdapterFactory;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemColorProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITableItemColorProvider;
import org.eclipse.emf.edit.provider.ITableItemLabelProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class EvidenceItemProviderAdapterFactory extends EvidenceAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public EvidenceItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
		supportedTypes.add(ITableItemLabelProvider.class);
		supportedTypes.add(ITableItemColorProvider.class);
		supportedTypes.add(IItemColorProvider.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.Consistency} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConsistencyItemProvider consistencyItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.Consistency}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConsistencyAdapter() {
		if (consistencyItemProvider == null) {
			consistencyItemProvider = new ConsistencyItemProvider(this);
		}

		return consistencyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.Completeness} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CompletenessItemProvider completenessItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.Completeness}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCompletenessAdapter() {
		if (completenessItemProvider == null) {
			completenessItemProvider = new CompletenessItemProvider(this);
		}

		return completenessItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.Document} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DocumentItemProvider documentItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.Document}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDocumentAdapter() {
		if (documentItemProvider == null) {
			documentItemProvider = new DocumentItemProvider(this);
		}

		return documentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.Confidence} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConfidenceItemProvider confidenceItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.Confidence}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConfidenceAdapter() {
		if (confidenceItemProvider == null) {
			confidenceItemProvider = new ConfidenceItemProvider(this);
		}

		return confidenceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.ApprovedBy} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ApprovedByItemProvider approvedByItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.ApprovedBy}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createApprovedByAdapter() {
		if (approvedByItemProvider == null) {
			approvedByItemProvider = new ApprovedByItemProvider(this);
		}

		return approvedByItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.Description} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DescriptionItemProvider descriptionItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.Description}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDescriptionAdapter() {
		if (descriptionItemProvider == null) {
			descriptionItemProvider = new DescriptionItemProvider(this);
		}

		return descriptionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.CreatedBy} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CreatedByItemProvider createdByItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.CreatedBy}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCreatedByAdapter() {
		if (createdByItemProvider == null) {
			createdByItemProvider = new CreatedByItemProvider(this);
		}

		return createdByItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.Tool} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ToolItemProvider toolItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.Tool}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createToolAdapter() {
		if (toolItemProvider == null) {
			toolItemProvider = new ToolItemProvider(this);
		}

		return toolItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.Method} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MethodItemProvider methodItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.Method}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMethodAdapter() {
		if (methodItemProvider == null) {
			methodItemProvider = new MethodItemProvider(this);
		}

		return methodItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.RequiresTool} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RequiresToolItemProvider requiresToolItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.RequiresTool}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRequiresToolAdapter() {
		if (requiresToolItemProvider == null) {
			requiresToolItemProvider = new RequiresToolItemProvider(this);
		}

		return requiresToolItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.IsBasedOn} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IsBasedOnItemProvider isBasedOnItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.IsBasedOn}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIsBasedOnAdapter() {
		if (isBasedOnItemProvider == null) {
			isBasedOnItemProvider = new IsBasedOnItemProvider(this);
		}

		return isBasedOnItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.IsA} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IsAItemProvider isAItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.IsA}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIsAAdapter() {
		if (isAItemProvider == null) {
			isAItemProvider = new IsAItemProvider(this);
		}

		return isAItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.IsCharacterizedBy} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IsCharacterizedByItemProvider isCharacterizedByItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.IsCharacterizedBy}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIsCharacterizedByAdapter() {
		if (isCharacterizedByItemProvider == null) {
			isCharacterizedByItemProvider = new IsCharacterizedByItemProvider(this);
		}

		return isCharacterizedByItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.Person} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PersonItemProvider personItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.Person}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPersonAdapter() {
		if (personItemProvider == null) {
			personItemProvider = new PersonItemProvider(this);
		}

		return personItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.Organization} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OrganizationItemProvider organizationItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.Organization}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOrganizationAdapter() {
		if (organizationItemProvider == null) {
			organizationItemProvider = new OrganizationItemProvider(this);
		}

		return organizationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.Package} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PackageItemProvider packageItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.Package}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPackageAdapter() {
		if (packageItemProvider == null) {
			packageItemProvider = new PackageItemProvider(this);
		}

		return packageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.EndTime} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EndTimeItemProvider endTimeItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.EndTime}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEndTimeAdapter() {
		if (endTimeItemProvider == null) {
			endTimeItemProvider = new EndTimeItemProvider(this);
		}

		return endTimeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.Assertion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AssertionItemProvider assertionItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.Assertion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAssertionAdapter() {
		if (assertionItemProvider == null) {
			assertionItemProvider = new AssertionItemProvider(this);
		}

		return assertionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.Object} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ObjectItemProvider objectItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.Object}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createObjectAdapter() {
		if (objectItemProvider == null) {
			objectItemProvider = new ObjectItemProvider(this);
		}

		return objectItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.CompositeSubject} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CompositeSubjectItemProvider compositeSubjectItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.CompositeSubject}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCompositeSubjectAdapter() {
		if (compositeSubjectItemProvider == null) {
			compositeSubjectItemProvider = new CompositeSubjectItemProvider(this);
		}

		return compositeSubjectItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.RoleBinding} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RoleBindingItemProvider roleBindingItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.RoleBinding}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRoleBindingAdapter() {
		if (roleBindingItemProvider == null) {
			roleBindingItemProvider = new RoleBindingItemProvider(this);
		}

		return roleBindingItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.StartTime} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StartTimeItemProvider startTimeItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.StartTime}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStartTimeAdapter() {
		if (startTimeItemProvider == null) {
			startTimeItemProvider = new StartTimeItemProvider(this);
		}

		return startTimeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.Relevance} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RelevanceItemProvider relevanceItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.Relevance}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRelevanceAdapter() {
		if (relevanceItemProvider == null) {
			relevanceItemProvider = new RelevanceItemProvider(this);
		}

		return relevanceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.Significance} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SignificanceItemProvider significanceItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.Significance}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSignificanceAdapter() {
		if (significanceItemProvider == null) {
			significanceItemProvider = new SignificanceItemProvider(this);
		}

		return significanceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.Accuracy} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AccuracyItemProvider accuracyItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.Accuracy}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAccuracyAdapter() {
		if (accuracyItemProvider == null) {
			accuracyItemProvider = new AccuracyItemProvider(this);
		}

		return accuracyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.HasRoleIn} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected HasRoleInItemProvider hasRoleInItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.HasRoleIn}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createHasRoleInAdapter() {
		if (hasRoleInItemProvider == null) {
			hasRoleInItemProvider = new HasRoleInItemProvider(this);
		}

		return hasRoleInItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.IsScopedBy} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IsScopedByItemProvider isScopedByItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.IsScopedBy}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIsScopedByAdapter() {
		if (isScopedByItemProvider == null) {
			isScopedByItemProvider = new IsScopedByItemProvider(this);
		}

		return isScopedByItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.AtTime} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AtTimeItemProvider atTimeItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.AtTime}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAtTimeAdapter() {
		if (atTimeItemProvider == null) {
			atTimeItemProvider = new AtTimeItemProvider(this);
		}

		return atTimeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.Originality} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OriginalityItemProvider originalityItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.Originality}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOriginalityAdapter() {
		if (originalityItemProvider == null) {
			originalityItemProvider = new OriginalityItemProvider(this);
		}

		return originalityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.Reporting} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReportingItemProvider reportingItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.Reporting}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReportingAdapter() {
		if (reportingItemProvider == null) {
			reportingItemProvider = new ReportingItemProvider(this);
		}

		return reportingItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.Reliability} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReliabilityItemProvider reliabilityItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.Reliability}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReliabilityAdapter() {
		if (reliabilityItemProvider == null) {
			reliabilityItemProvider = new ReliabilityItemProvider(this);
		}

		return reliabilityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.Supports} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SupportsItemProvider supportsItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.Supports}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSupportsAdapter() {
		if (supportsItemProvider == null) {
			supportsItemProvider = new SupportsItemProvider(this);
		}

		return supportsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.IsGeneratedAt} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IsGeneratedAtItemProvider isGeneratedAtItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.IsGeneratedAt}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIsGeneratedAtAdapter() {
		if (isGeneratedAtItemProvider == null) {
			isGeneratedAtItemProvider = new IsGeneratedAtItemProvider(this);
		}

		return isGeneratedAtItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.Support} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SupportItemProvider supportItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.Support}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSupportAdapter() {
		if (supportItemProvider == null) {
			supportItemProvider = new SupportItemProvider(this);
		}

		return supportItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.Conflicts} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConflictsItemProvider conflictsItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.Conflicts}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConflictsAdapter() {
		if (conflictsItemProvider == null) {
			conflictsItemProvider = new ConflictsItemProvider(this);
		}

		return conflictsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.Rationale} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RationaleItemProvider rationaleItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.Rationale}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRationaleAdapter() {
		if (rationaleItemProvider == null) {
			rationaleItemProvider = new RationaleItemProvider(this);
		}

		return rationaleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.Refutes} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RefutesItemProvider refutesItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.Refutes}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRefutesAdapter() {
		if (refutesItemProvider == null) {
			refutesItemProvider = new RefutesItemProvider(this);
		}

		return refutesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.Negates} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NegatesItemProvider negatesItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.Negates}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNegatesAdapter() {
		if (negatesItemProvider == null) {
			negatesItemProvider = new NegatesItemProvider(this);
		}

		return negatesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.UnknownSubject} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UnknownSubjectItemProvider unknownSubjectItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.UnknownSubject}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUnknownSubjectAdapter() {
		if (unknownSubjectItemProvider == null) {
			unknownSubjectItemProvider = new UnknownSubjectItemProvider(this);
		}

		return unknownSubjectItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.Resolves} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ResolvesItemProvider resolvesItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.Resolves}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createResolvesAdapter() {
		if (resolvesItemProvider == null) {
			resolvesItemProvider = new ResolvesItemProvider(this);
		}

		return resolvesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.EvidenceRequest} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EvidenceRequestItemProvider evidenceRequestItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.EvidenceRequest}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEvidenceRequestAdapter() {
		if (evidenceRequestItemProvider == null) {
			evidenceRequestItemProvider = new EvidenceRequestItemProvider(this);
		}

		return evidenceRequestItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.ProjectObjective} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ProjectObjectiveItemProvider projectObjectiveItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.ProjectObjective}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createProjectObjectiveAdapter() {
		if (projectObjectiveItemProvider == null) {
			projectObjectiveItemProvider = new ProjectObjectiveItemProvider(this);
		}

		return projectObjectiveItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.Activity} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ActivityItemProvider activityItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.Activity}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createActivityAdapter() {
		if (activityItemProvider == null) {
			activityItemProvider = new ActivityItemProvider(this);
		}

		return activityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.DependsOn} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DependsOnItemProvider dependsOnItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.DependsOn}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDependsOnAdapter() {
		if (dependsOnItemProvider == null) {
			dependsOnItemProvider = new DependsOnItemProvider(this);
		}

		return dependsOnItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.IsAssociatedWith} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IsAssociatedWithItemProvider isAssociatedWithItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.IsAssociatedWith}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIsAssociatedWithAdapter() {
		if (isAssociatedWithItemProvider == null) {
			isAssociatedWithItemProvider = new IsAssociatedWithItemProvider(this);
		}

		return isAssociatedWithItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.RequiresMethod} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RequiresMethodItemProvider requiresMethodItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.RequiresMethod}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRequiresMethodAdapter() {
		if (requiresMethodItemProvider == null) {
			requiresMethodItemProvider = new RequiresMethodItemProvider(this);
		}

		return requiresMethodItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.Satisfies} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SatisfiesItemProvider satisfiesItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.Satisfies}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSatisfiesAdapter() {
		if (satisfiesItemProvider == null) {
			satisfiesItemProvider = new SatisfiesItemProvider(this);
		}

		return satisfiesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.DomainClaim} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DomainClaimItemProvider domainClaimItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.DomainClaim}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDomainClaimAdapter() {
		if (domainClaimItemProvider == null) {
			domainClaimItemProvider = new DomainClaimItemProvider(this);
		}

		return domainClaimItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.Weakens} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WeakensItemProvider weakensItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.Weakens}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createWeakensAdapter() {
		if (weakensItemProvider == null) {
			weakensItemProvider = new WeakensItemProvider(this);
		}

		return weakensItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.Amplifies} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AmplifiesItemProvider amplifiesItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.Amplifies}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAmplifiesAdapter() {
		if (amplifiesItemProvider == null) {
			amplifiesItemProvider = new AmplifiesItemProvider(this);
		}

		return amplifiesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.Challenges} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ChallengesItemProvider challengesItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.Challenges}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createChallengesAdapter() {
		if (challengesItemProvider == null) {
			challengesItemProvider = new ChallengesItemProvider(this);
		}

		return challengesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.Strength} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StrengthItemProvider strengthItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.Strength}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStrengthAdapter() {
		if (strengthItemProvider == null) {
			strengthItemProvider = new StrengthItemProvider(this);
		}

		return strengthItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.IsAcquiredAt} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IsAcquiredAtItemProvider isAcquiredAtItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.IsAcquiredAt}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIsAcquiredAtAdapter() {
		if (isAcquiredAtItemProvider == null) {
			isAcquiredAtItemProvider = new IsAcquiredAtItemProvider(this);
		}

		return isAcquiredAtItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.IsTransferredTo} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IsTransferredToItemProvider isTransferredToItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.IsTransferredTo}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIsTransferredToAdapter() {
		if (isTransferredToItemProvider == null) {
			isTransferredToItemProvider = new IsTransferredToItemProvider(this);
		}

		return isTransferredToItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.OwnedBy} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OwnedByItemProvider ownedByItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.OwnedBy}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOwnedByAdapter() {
		if (ownedByItemProvider == null) {
			ownedByItemProvider = new OwnedByItemProvider(this);
		}

		return ownedByItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.IsPartOf} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IsPartOfItemProvider isPartOfItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.IsPartOf}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIsPartOfAdapter() {
		if (isPartOfItemProvider == null) {
			isPartOfItemProvider = new IsPartOfItemProvider(this);
		}

		return isPartOfItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.IsRevokedAt} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IsRevokedAtItemProvider isRevokedAtItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.IsRevokedAt}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIsRevokedAtAdapter() {
		if (isRevokedAtItemProvider == null) {
			isRevokedAtItemProvider = new IsRevokedAtItemProvider(this);
		}

		return isRevokedAtItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.ProvidesContext} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ProvidesContextItemProvider providesContextItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.ProvidesContext}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createProvidesContextAdapter() {
		if (providesContextItemProvider == null) {
			providesContextItemProvider = new ProvidesContextItemProvider(this);
		}

		return providesContextItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.MeansThat} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MeansThatItemProvider meansThatItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.MeansThat}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMeansThatAdapter() {
		if (meansThatItemProvider == null) {
			meansThatItemProvider = new MeansThatItemProvider(this);
		}

		return meansThatItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.CareOf} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CareOfItemProvider careOfItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.CareOf}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCareOfAdapter() {
		if (careOfItemProvider == null) {
			careOfItemProvider = new CareOfItemProvider(this);
		}

		return careOfItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.AtLocation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AtLocationItemProvider atLocationItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.AtLocation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAtLocationAdapter() {
		if (atLocationItemProvider == null) {
			atLocationItemProvider = new AtLocationItemProvider(this);
		}

		return atLocationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.IsCreatedAt} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IsCreatedAtItemProvider isCreatedAtItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.IsCreatedAt}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIsCreatedAtAdapter() {
		if (isCreatedAtItemProvider == null) {
			isCreatedAtItemProvider = new IsCreatedAtItemProvider(this);
		}

		return isCreatedAtItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.RequiresPackage} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RequiresPackageItemProvider requiresPackageItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.RequiresPackage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRequiresPackageAdapter() {
		if (requiresPackageItemProvider == null) {
			requiresPackageItemProvider = new RequiresPackageItemProvider(this);
		}

		return requiresPackageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.Service} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ServiceItemProvider serviceItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.Service}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createServiceAdapter() {
		if (serviceItemProvider == null) {
			serviceItemProvider = new ServiceItemProvider(this);
		}

		return serviceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.HasElectronicSource} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected HasElectronicSourceItemProvider hasElectronicSourceItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.HasElectronicSource}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createHasElectronicSourceAdapter() {
		if (hasElectronicSourceItemProvider == null) {
			hasElectronicSourceItemProvider = new HasElectronicSourceItemProvider(this);
		}

		return hasElectronicSourceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.IsExpressedInLanguage} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IsExpressedInLanguageItemProvider isExpressedInLanguageItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.IsExpressedInLanguage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIsExpressedInLanguageAdapter() {
		if (isExpressedInLanguageItemProvider == null) {
			isExpressedInLanguageItemProvider = new IsExpressedInLanguageItemProvider(this);
		}

		return isExpressedInLanguageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.UsingProcess} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UsingProcessItemProvider usingProcessItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.UsingProcess}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUsingProcessAdapter() {
		if (usingProcessItemProvider == null) {
			usingProcessItemProvider = new UsingProcessItemProvider(this);
		}

		return usingProcessItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.HasSecurityClassification} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected HasSecurityClassificationItemProvider hasSecurityClassificationItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.HasSecurityClassification}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createHasSecurityClassificationAdapter() {
		if (hasSecurityClassificationItemProvider == null) {
			hasSecurityClassificationItemProvider = new HasSecurityClassificationItemProvider(this);
		}

		return hasSecurityClassificationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.IsReleaseableTo} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IsReleaseableToItemProvider isReleaseableToItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.IsReleaseableTo}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIsReleaseableToAdapter() {
		if (isReleaseableToItemProvider == null) {
			isReleaseableToItemProvider = new IsReleaseableToItemProvider(this);
		}

		return isReleaseableToItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.EvidenceGroup} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EvidenceGroupItemProvider evidenceGroupItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.EvidenceGroup}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEvidenceGroupAdapter() {
		if (evidenceGroupItemProvider == null) {
			evidenceGroupItemProvider = new EvidenceGroupItemProvider(this);
		}

		return evidenceGroupItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.HasVersion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected HasVersionItemProvider hasVersionItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.HasVersion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createHasVersionAdapter() {
		if (hasVersionItemProvider == null) {
			hasVersionItemProvider = new HasVersionItemProvider(this);
		}

		return hasVersionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.EvaluationAttribute} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EvaluationAttributeItemProvider evaluationAttributeItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.EvaluationAttribute}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEvaluationAttributeAdapter() {
		if (evaluationAttributeItemProvider == null) {
			evaluationAttributeItemProvider = new EvaluationAttributeItemProvider(this);
		}

		return evaluationAttributeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.Supercedes} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SupercedesItemProvider supercedesItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.Supercedes}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSupercedesAdapter() {
		if (supercedesItemProvider == null) {
			supercedesItemProvider = new SupercedesItemProvider(this);
		}

		return supercedesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.HasMedia} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected HasMediaItemProvider hasMediaItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.HasMedia}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createHasMediaAdapter() {
		if (hasMediaItemProvider == null) {
			hasMediaItemProvider = new HasMediaItemProvider(this);
		}

		return hasMediaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link net.certware.evidence.evidence.Exhibit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExhibitItemProvider exhibitItemProvider;

	/**
	 * This creates an adapter for a {@link net.certware.evidence.evidence.Exhibit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExhibitAdapter() {
		if (exhibitItemProvider == null) {
			exhibitItemProvider = new ExhibitItemProvider(this);
		}

		return exhibitItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (consistencyItemProvider != null) consistencyItemProvider.dispose();
		if (completenessItemProvider != null) completenessItemProvider.dispose();
		if (documentItemProvider != null) documentItemProvider.dispose();
		if (confidenceItemProvider != null) confidenceItemProvider.dispose();
		if (approvedByItemProvider != null) approvedByItemProvider.dispose();
		if (descriptionItemProvider != null) descriptionItemProvider.dispose();
		if (createdByItemProvider != null) createdByItemProvider.dispose();
		if (toolItemProvider != null) toolItemProvider.dispose();
		if (methodItemProvider != null) methodItemProvider.dispose();
		if (requiresToolItemProvider != null) requiresToolItemProvider.dispose();
		if (isBasedOnItemProvider != null) isBasedOnItemProvider.dispose();
		if (isAItemProvider != null) isAItemProvider.dispose();
		if (isCharacterizedByItemProvider != null) isCharacterizedByItemProvider.dispose();
		if (personItemProvider != null) personItemProvider.dispose();
		if (organizationItemProvider != null) organizationItemProvider.dispose();
		if (packageItemProvider != null) packageItemProvider.dispose();
		if (endTimeItemProvider != null) endTimeItemProvider.dispose();
		if (assertionItemProvider != null) assertionItemProvider.dispose();
		if (objectItemProvider != null) objectItemProvider.dispose();
		if (compositeSubjectItemProvider != null) compositeSubjectItemProvider.dispose();
		if (roleBindingItemProvider != null) roleBindingItemProvider.dispose();
		if (startTimeItemProvider != null) startTimeItemProvider.dispose();
		if (relevanceItemProvider != null) relevanceItemProvider.dispose();
		if (significanceItemProvider != null) significanceItemProvider.dispose();
		if (accuracyItemProvider != null) accuracyItemProvider.dispose();
		if (hasRoleInItemProvider != null) hasRoleInItemProvider.dispose();
		if (isScopedByItemProvider != null) isScopedByItemProvider.dispose();
		if (atTimeItemProvider != null) atTimeItemProvider.dispose();
		if (originalityItemProvider != null) originalityItemProvider.dispose();
		if (reportingItemProvider != null) reportingItemProvider.dispose();
		if (reliabilityItemProvider != null) reliabilityItemProvider.dispose();
		if (supportsItemProvider != null) supportsItemProvider.dispose();
		if (isGeneratedAtItemProvider != null) isGeneratedAtItemProvider.dispose();
		if (supportItemProvider != null) supportItemProvider.dispose();
		if (conflictsItemProvider != null) conflictsItemProvider.dispose();
		if (rationaleItemProvider != null) rationaleItemProvider.dispose();
		if (refutesItemProvider != null) refutesItemProvider.dispose();
		if (negatesItemProvider != null) negatesItemProvider.dispose();
		if (unknownSubjectItemProvider != null) unknownSubjectItemProvider.dispose();
		if (resolvesItemProvider != null) resolvesItemProvider.dispose();
		if (evidenceRequestItemProvider != null) evidenceRequestItemProvider.dispose();
		if (projectObjectiveItemProvider != null) projectObjectiveItemProvider.dispose();
		if (activityItemProvider != null) activityItemProvider.dispose();
		if (dependsOnItemProvider != null) dependsOnItemProvider.dispose();
		if (isAssociatedWithItemProvider != null) isAssociatedWithItemProvider.dispose();
		if (requiresMethodItemProvider != null) requiresMethodItemProvider.dispose();
		if (satisfiesItemProvider != null) satisfiesItemProvider.dispose();
		if (domainClaimItemProvider != null) domainClaimItemProvider.dispose();
		if (weakensItemProvider != null) weakensItemProvider.dispose();
		if (amplifiesItemProvider != null) amplifiesItemProvider.dispose();
		if (challengesItemProvider != null) challengesItemProvider.dispose();
		if (strengthItemProvider != null) strengthItemProvider.dispose();
		if (isAcquiredAtItemProvider != null) isAcquiredAtItemProvider.dispose();
		if (isTransferredToItemProvider != null) isTransferredToItemProvider.dispose();
		if (ownedByItemProvider != null) ownedByItemProvider.dispose();
		if (isPartOfItemProvider != null) isPartOfItemProvider.dispose();
		if (isRevokedAtItemProvider != null) isRevokedAtItemProvider.dispose();
		if (providesContextItemProvider != null) providesContextItemProvider.dispose();
		if (meansThatItemProvider != null) meansThatItemProvider.dispose();
		if (careOfItemProvider != null) careOfItemProvider.dispose();
		if (atLocationItemProvider != null) atLocationItemProvider.dispose();
		if (isCreatedAtItemProvider != null) isCreatedAtItemProvider.dispose();
		if (requiresPackageItemProvider != null) requiresPackageItemProvider.dispose();
		if (serviceItemProvider != null) serviceItemProvider.dispose();
		if (hasElectronicSourceItemProvider != null) hasElectronicSourceItemProvider.dispose();
		if (isExpressedInLanguageItemProvider != null) isExpressedInLanguageItemProvider.dispose();
		if (usingProcessItemProvider != null) usingProcessItemProvider.dispose();
		if (hasSecurityClassificationItemProvider != null) hasSecurityClassificationItemProvider.dispose();
		if (isReleaseableToItemProvider != null) isReleaseableToItemProvider.dispose();
		if (evidenceGroupItemProvider != null) evidenceGroupItemProvider.dispose();
		if (hasVersionItemProvider != null) hasVersionItemProvider.dispose();
		if (evaluationAttributeItemProvider != null) evaluationAttributeItemProvider.dispose();
		if (supercedesItemProvider != null) supercedesItemProvider.dispose();
		if (hasMediaItemProvider != null) hasMediaItemProvider.dispose();
		if (exhibitItemProvider != null) exhibitItemProvider.dispose();
	}

}
