/*
 * generated by Xtext
 */
package net.certware.argument.sfp;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SemiFormalProofRuntimeModule extends net.certware.argument.sfp.AbstractSemiFormalProofRuntimeModule {

}
