/*
* generated by Xtext
*/
package net.certware.argument.sfp.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SemiFormalProofAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("net/certware/argument/sfp/parser/antlr/internal/InternalSemiFormalProof.tokens");
	}
}
