/*
 * generated by Xtext
 */
package net.certware.argument.sfp.formatting;

import net.certware.argument.sfp.services.SemiFormalProofGrammarAccess;

import org.eclipse.xtext.formatting.impl.AbstractDeclarativeFormatter;
import org.eclipse.xtext.formatting.impl.FormattingConfig;

/**
 * This class contains custom formatting description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#formatting
 * on how and when to use it 
 * 
 * Also see {@link org.eclipse.xtext.xtext.XtextFormattingTokenSerializer} as an example
 */
public class SemiFormalProofFormatter extends AbstractDeclarativeFormatter {
	
	@Override
	protected void configureFormatting(FormattingConfig c) {
		
		SemiFormalProofGrammarAccess f = (SemiFormalProofGrammarAccess) getGrammarAccess();
		
		c.setLinewrap(0, 1, 2).before(f.getSL_COMMENTRule());
		c.setLinewrap(0, 1, 2).before(f.getML_COMMENTRule());
		c.setLinewrap(0, 1, 1).after(f.getML_COMMENTRule());
		
		c.setLinewrap(0,1,2).before(f.getStatementRule()); // TODO testing usefulness
	}
}
