/*
 * generated by Xtext
 */
package net.certware.planning.cpn;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CpnDslRuntimeModule extends net.certware.planning.cpn.AbstractCpnDslRuntimeModule {

}
