/*
 * generated by Xtext
 */
package net.certware.hazard.stpa.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import net.certware.hazard.stpa.ui.internal.HazardAnalysisActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class HazardAnalysisExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return HazardAnalysisActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return HazardAnalysisActivator.getInstance().getInjector(HazardAnalysisActivator.NET_CERTWARE_HAZARD_STPA_HAZARDANALYSIS);
	}
	
}
