/*
 * generated by Xtext
 */
package net.certware.intent.state.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class StateSpecificationUiModule extends net.certware.intent.state.ui.AbstractStateSpecificationUiModule {
	public StateSpecificationUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
