/*
* generated by Xtext
*/
package net.certware.evidence.hugin.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import net.certware.evidence.hugin.services.NetDSLGrammarAccess;

public class NetDSLParser extends AbstractContentAssistParser {
	
	@Inject
	private NetDSLGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected net.certware.evidence.hugin.ui.contentassist.antlr.internal.InternalNetDSLParser createParser() {
		net.certware.evidence.hugin.ui.contentassist.antlr.internal.InternalNetDSLParser result = new net.certware.evidence.hugin.ui.contentassist.antlr.internal.InternalNetDSLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getSignAccess().getAlternatives(), "rule__Sign__Alternatives");
					put(grammarAccess.getDomainElementAccess().getAlternatives(), "rule__DomainElement__Alternatives");
					put(grammarAccess.getAttributeAccess().getAlternatives(), "rule__Attribute__Alternatives");
					put(grammarAccess.getBasicNodeKeywordAccess().getAlternatives(), "rule__BasicNodeKeyword__Alternatives");
					put(grammarAccess.getBasicNodeKeywordAccess().getAlternatives_0_0(), "rule__BasicNodeKeyword__Alternatives_0_0");
					put(grammarAccess.getSubtypeAttributeAccess().getSubtypeAlternatives_2_0(), "rule__SubtypeAttribute__SubtypeAlternatives_2_0");
					put(grammarAccess.getPotentialAttributeAccess().getAlternatives(), "rule__PotentialAttribute__Alternatives");
					put(grammarAccess.getPotentialDataAttributeAccess().getAlternatives_4(), "rule__PotentialDataAttribute__Alternatives_4");
					put(grammarAccess.getUnstructuredDataListAccess().getAlternatives(), "rule__UnstructuredDataList__Alternatives");
					put(grammarAccess.getStructuredDataListAccess().getAlternatives_2(), "rule__StructuredDataList__Alternatives_2");
					put(grammarAccess.getMeanTermAccess().getAlternatives(), "rule__MeanTerm__Alternatives");
					put(grammarAccess.getClassElementAccess().getAlternatives(), "rule__ClassElement__Alternatives");
					put(grammarAccess.getNodeAttributesAccess().getAlternatives(), "rule__NodeAttributes__Alternatives");
					put(grammarAccess.getFactorAccess().getAlternatives(), "rule__Factor__Alternatives");
					put(grammarAccess.getComparisonAccess().getAlternatives(), "rule__Comparison__Alternatives");
					put(grammarAccess.getPlusOrMinusAccess().getAlternatives(), "rule__PlusOrMinus__Alternatives");
					put(grammarAccess.getTimesOrDivideAccess().getAlternatives(), "rule__TimesOrDivide__Alternatives");
					put(grammarAccess.getOperatorNameAccess().getAlternatives(), "rule__OperatorName__Alternatives");
					put(grammarAccess.getFloatAccess().getGroup(), "rule__Float__Group__0");
					put(grammarAccess.getFloatAccess().getGroup_2(), "rule__Float__Group_2__0");
					put(grammarAccess.getDomainDefinitionAccess().getGroup(), "rule__DomainDefinition__Group__0");
					put(grammarAccess.getDomainHeaderAccess().getGroup(), "rule__DomainHeader__Group__0");
					put(grammarAccess.getBasicNodeAccess().getGroup(), "rule__BasicNode__Group__0");
					put(grammarAccess.getBasicNodeKeywordAccess().getGroup_0(), "rule__BasicNodeKeyword__Group_0__0");
					put(grammarAccess.getStatesAttributeAccess().getGroup(), "rule__StatesAttribute__Group__0");
					put(grammarAccess.getLabelAttributeAccess().getGroup(), "rule__LabelAttribute__Group__0");
					put(grammarAccess.getPositionAttributeAccess().getGroup(), "rule__PositionAttribute__Group__0");
					put(grammarAccess.getSubtypeAttributeAccess().getGroup(), "rule__SubtypeAttribute__Group__0");
					put(grammarAccess.getStateValuesAttributeAccess().getGroup(), "rule__StateValuesAttribute__Group__0");
					put(grammarAccess.getApplicationAttributeAccess().getGroup(), "rule__ApplicationAttribute__Group__0");
					put(grammarAccess.getNodeSizeAttributeAccess().getGroup(), "rule__NodeSizeAttribute__Group__0");
					put(grammarAccess.getPotentialAccess().getGroup(), "rule__Potential__Group__0");
					put(grammarAccess.getPotentialGraphAccess().getGroup(), "rule__PotentialGraph__Group__0");
					put(grammarAccess.getPotentialGraphAccess().getGroup_3(), "rule__PotentialGraph__Group_3__0");
					put(grammarAccess.getPotentialModelAccess().getGroup(), "rule__PotentialModel__Group__0");
					put(grammarAccess.getPotentialDataAttributeAccess().getGroup(), "rule__PotentialDataAttribute__Group__0");
					put(grammarAccess.getUnstructuredDataListAccess().getGroup_0(), "rule__UnstructuredDataList__Group_0__0");
					put(grammarAccess.getStructuredDataListAccess().getGroup(), "rule__StructuredDataList__Group__0");
					put(grammarAccess.getFloatDataListAccess().getGroup(), "rule__FloatDataList__Group__0");
					put(grammarAccess.getNormalDistributionAccess().getGroup(), "rule__NormalDistribution__Group__0");
					put(grammarAccess.getMeanExpressionAccess().getGroup(), "rule__MeanExpression__Group__0");
					put(grammarAccess.getMeanExpressionAccess().getGroup_1(), "rule__MeanExpression__Group_1__0");
					put(grammarAccess.getMeanTermAccess().getGroup_1(), "rule__MeanTerm__Group_1__0");
					put(grammarAccess.getPotentialTableAttributeAccess().getGroup(), "rule__PotentialTableAttribute__Group__0");
					put(grammarAccess.getModelNodesAttributeAccess().getGroup(), "rule__ModelNodesAttribute__Group__0");
					put(grammarAccess.getSamplesAttributeAccess().getGroup(), "rule__SamplesAttribute__Group__0");
					put(grammarAccess.getModelDataAttributeAccess().getGroup(), "rule__ModelDataAttribute__Group__0");
					put(grammarAccess.getClassDefinitionAccess().getGroup(), "rule__ClassDefinition__Group__0");
					put(grammarAccess.getClassInstanceAccess().getGroup(), "rule__ClassInstance__Group__0");
					put(grammarAccess.getClassInstanceAccess().getGroup_6(), "rule__ClassInstance__Group_6__0");
					put(grammarAccess.getInputBindingsAccess().getGroup(), "rule__InputBindings__Group__0");
					put(grammarAccess.getInputBindingAccess().getGroup(), "rule__InputBinding__Group__0");
					put(grammarAccess.getOutputBindingsAccess().getGroup(), "rule__OutputBindings__Group__0");
					put(grammarAccess.getOutputBindingAccess().getGroup(), "rule__OutputBinding__Group__0");
					put(grammarAccess.getExpressionAccess().getGroup(), "rule__Expression__Group__0");
					put(grammarAccess.getExpressionAccess().getGroup_1(), "rule__Expression__Group_1__0");
					put(grammarAccess.getSimpleExpressionAccess().getGroup(), "rule__SimpleExpression__Group__0");
					put(grammarAccess.getSimpleExpressionAccess().getGroup_1(), "rule__SimpleExpression__Group_1__0");
					put(grammarAccess.getTermAccess().getGroup(), "rule__Term__Group__0");
					put(grammarAccess.getTermAccess().getGroup_1(), "rule__Term__Group_1__0");
					put(grammarAccess.getExpFactorAccess().getGroup(), "rule__ExpFactor__Group__0");
					put(grammarAccess.getExpFactorAccess().getGroup_1(), "rule__ExpFactor__Group_1__0");
					put(grammarAccess.getFactorAccess().getGroup_0(), "rule__Factor__Group_0__0");
					put(grammarAccess.getFactorAccess().getGroup_5(), "rule__Factor__Group_5__0");
					put(grammarAccess.getFactorAccess().getGroup_6(), "rule__Factor__Group_6__0");
					put(grammarAccess.getExpressionSequenceAccess().getGroup(), "rule__ExpressionSequence__Group__0");
					put(grammarAccess.getExpressionSequenceAccess().getGroup_1(), "rule__ExpressionSequence__Group_1__0");
					put(grammarAccess.getExpressionSequenceAccess().getGroup_1_1(), "rule__ExpressionSequence__Group_1_1__0");
					put(grammarAccess.getOperatorNameAccess().getGroup_14(), "rule__OperatorName__Group_14__0");
					put(grammarAccess.getModelAccess().getDomainAssignment(), "rule__Model__DomainAssignment");
					put(grammarAccess.getDomainDefinitionAccess().getHeaderAssignment_0(), "rule__DomainDefinition__HeaderAssignment_0");
					put(grammarAccess.getDomainDefinitionAccess().getElementsAssignment_1(), "rule__DomainDefinition__ElementsAssignment_1");
					put(grammarAccess.getDomainHeaderAccess().getAttributesAssignment_3(), "rule__DomainHeader__AttributesAssignment_3");
					put(grammarAccess.getBasicNodeAccess().getKeywordAssignment_0(), "rule__BasicNode__KeywordAssignment_0");
					put(grammarAccess.getBasicNodeAccess().getIdAssignment_1(), "rule__BasicNode__IdAssignment_1");
					put(grammarAccess.getBasicNodeAccess().getAttributesAssignment_3(), "rule__BasicNode__AttributesAssignment_3");
					put(grammarAccess.getStatesAttributeAccess().getStatesAssignment_4(), "rule__StatesAttribute__StatesAssignment_4");
					put(grammarAccess.getLabelAttributeAccess().getValueAssignment_2(), "rule__LabelAttribute__ValueAssignment_2");
					put(grammarAccess.getPositionAttributeAccess().getXAssignment_3(), "rule__PositionAttribute__XAssignment_3");
					put(grammarAccess.getPositionAttributeAccess().getYAssignment_4(), "rule__PositionAttribute__YAssignment_4");
					put(grammarAccess.getSubtypeAttributeAccess().getSubtypeAssignment_2(), "rule__SubtypeAttribute__SubtypeAssignment_2");
					put(grammarAccess.getStateValuesAttributeAccess().getNumbersAssignment_3(), "rule__StateValuesAttribute__NumbersAssignment_3");
					put(grammarAccess.getApplicationAttributeAccess().getKeyAssignment_0(), "rule__ApplicationAttribute__KeyAssignment_0");
					put(grammarAccess.getApplicationAttributeAccess().getValueAssignment_2(), "rule__ApplicationAttribute__ValueAssignment_2");
					put(grammarAccess.getNodeSizeAttributeAccess().getWidthAssignment_3(), "rule__NodeSizeAttribute__WidthAssignment_3");
					put(grammarAccess.getNodeSizeAttributeAccess().getHeightAssignment_4(), "rule__NodeSizeAttribute__HeightAssignment_4");
					put(grammarAccess.getPotentialAccess().getGraphAssignment_1(), "rule__Potential__GraphAssignment_1");
					put(grammarAccess.getPotentialAccess().getModelAssignment_2(), "rule__Potential__ModelAssignment_2");
					put(grammarAccess.getPotentialGraphAccess().getChildrenAssignment_2(), "rule__PotentialGraph__ChildrenAssignment_2");
					put(grammarAccess.getPotentialGraphAccess().getParentsAssignment_3_1(), "rule__PotentialGraph__ParentsAssignment_3_1");
					put(grammarAccess.getPotentialModelAccess().getAttributesAssignment_2(), "rule__PotentialModel__AttributesAssignment_2");
					put(grammarAccess.getPotentialDataAttributeAccess().getUnstructuredAssignment_4_0(), "rule__PotentialDataAttribute__UnstructuredAssignment_4_0");
					put(grammarAccess.getPotentialDataAttributeAccess().getItemsAssignment_4_1(), "rule__PotentialDataAttribute__ItemsAssignment_4_1");
					put(grammarAccess.getUnstructuredDataListAccess().getListAssignment_0_1(), "rule__UnstructuredDataList__ListAssignment_0_1");
					put(grammarAccess.getUnstructuredDataListAccess().getNormalAssignment_1(), "rule__UnstructuredDataList__NormalAssignment_1");
					put(grammarAccess.getStructuredDataListAccess().getListAssignment_2_0(), "rule__StructuredDataList__ListAssignment_2_0");
					put(grammarAccess.getStructuredDataListAccess().getItemsAssignment_2_1(), "rule__StructuredDataList__ItemsAssignment_2_1");
					put(grammarAccess.getFloatDataListAccess().getItemsAssignment_1(), "rule__FloatDataList__ItemsAssignment_1");
					put(grammarAccess.getNormalDistributionAccess().getMeanAssignment_2(), "rule__NormalDistribution__MeanAssignment_2");
					put(grammarAccess.getNormalDistributionAccess().getVarianceAssignment_4(), "rule__NormalDistribution__VarianceAssignment_4");
					put(grammarAccess.getPotentialTableAttributeAccess().getNodesAssignment_0(), "rule__PotentialTableAttribute__NodesAssignment_0");
					put(grammarAccess.getPotentialTableAttributeAccess().getSamplesAssignment_1(), "rule__PotentialTableAttribute__SamplesAssignment_1");
					put(grammarAccess.getPotentialTableAttributeAccess().getDataAssignment_2(), "rule__PotentialTableAttribute__DataAssignment_2");
					put(grammarAccess.getModelNodesAttributeAccess().getConfigurationsAssignment_4(), "rule__ModelNodesAttribute__ConfigurationsAssignment_4");
					put(grammarAccess.getSamplesAttributeAccess().getValueAssignment_2(), "rule__SamplesAttribute__ValueAssignment_2");
					put(grammarAccess.getClassDefinitionAccess().getNameAssignment_1(), "rule__ClassDefinition__NameAssignment_1");
					put(grammarAccess.getClassDefinitionAccess().getElementsAssignment_3(), "rule__ClassDefinition__ElementsAssignment_3");
					put(grammarAccess.getClassInstanceAccess().getInstanceNameAssignment_1(), "rule__ClassInstance__InstanceNameAssignment_1");
					put(grammarAccess.getClassInstanceAccess().getClassNameAssignment_3(), "rule__ClassInstance__ClassNameAssignment_3");
					put(grammarAccess.getClassInstanceAccess().getInputAssignment_5(), "rule__ClassInstance__InputAssignment_5");
					put(grammarAccess.getClassInstanceAccess().getOutputAssignment_6_1(), "rule__ClassInstance__OutputAssignment_6_1");
					put(grammarAccess.getClassInstanceAccess().getAttributesAssignment_9(), "rule__ClassInstance__AttributesAssignment_9");
					put(grammarAccess.getInputBindingsAccess().getLhsAssignment_0(), "rule__InputBindings__LhsAssignment_0");
					put(grammarAccess.getInputBindingsAccess().getRhsAssignment_2(), "rule__InputBindings__RhsAssignment_2");
					put(grammarAccess.getInputBindingAccess().getFormalAssignment_0(), "rule__InputBinding__FormalAssignment_0");
					put(grammarAccess.getInputBindingAccess().getActualAssignment_2(), "rule__InputBinding__ActualAssignment_2");
					put(grammarAccess.getOutputBindingsAccess().getLhsAssignment_0(), "rule__OutputBindings__LhsAssignment_0");
					put(grammarAccess.getOutputBindingsAccess().getRhsAssignment_2(), "rule__OutputBindings__RhsAssignment_2");
					put(grammarAccess.getOutputBindingAccess().getActualAssignment_0(), "rule__OutputBinding__ActualAssignment_0");
					put(grammarAccess.getOutputBindingAccess().getFormalAssignment_2(), "rule__OutputBinding__FormalAssignment_2");
					put(grammarAccess.getExpressionAccess().getLhsAssignment_0(), "rule__Expression__LhsAssignment_0");
					put(grammarAccess.getExpressionAccess().getRhsAssignment_1_1(), "rule__Expression__RhsAssignment_1_1");
					put(grammarAccess.getSimpleExpressionAccess().getLhsAssignment_0(), "rule__SimpleExpression__LhsAssignment_0");
					put(grammarAccess.getSimpleExpressionAccess().getRhsAssignment_1_1(), "rule__SimpleExpression__RhsAssignment_1_1");
					put(grammarAccess.getTermAccess().getLhsAssignment_0(), "rule__Term__LhsAssignment_0");
					put(grammarAccess.getTermAccess().getRhsAssignment_1_1(), "rule__Term__RhsAssignment_1_1");
					put(grammarAccess.getExpFactorAccess().getLhsAssignment_0(), "rule__ExpFactor__LhsAssignment_0");
					put(grammarAccess.getExpFactorAccess().getRhsAssignment_1_1(), "rule__ExpFactor__RhsAssignment_1_1");
					put(grammarAccess.getFactorAccess().getNumberAssignment_0_1(), "rule__Factor__NumberAssignment_0_1");
					put(grammarAccess.getFactorAccess().getNodeNameAssignment_1(), "rule__Factor__NodeNameAssignment_1");
					put(grammarAccess.getFactorAccess().getValueAssignment_2(), "rule__Factor__ValueAssignment_2");
					put(grammarAccess.getFactorAccess().getValueAssignment_3(), "rule__Factor__ValueAssignment_3");
					put(grammarAccess.getFactorAccess().getValueAssignment_4(), "rule__Factor__ValueAssignment_4");
					put(grammarAccess.getFactorAccess().getExpressionAssignment_5_1(), "rule__Factor__ExpressionAssignment_5_1");
					put(grammarAccess.getFactorAccess().getOpAssignment_6_0(), "rule__Factor__OpAssignment_6_0");
					put(grammarAccess.getFactorAccess().getSequenceAssignment_6_2(), "rule__Factor__SequenceAssignment_6_2");
					put(grammarAccess.getExpressionSequenceAccess().getExpressionsAssignment_1_0(), "rule__ExpressionSequence__ExpressionsAssignment_1_0");
					put(grammarAccess.getExpressionSequenceAccess().getExpressionsAssignment_1_1_1(), "rule__ExpressionSequence__ExpressionsAssignment_1_1_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			net.certware.evidence.hugin.ui.contentassist.antlr.internal.InternalNetDSLParser typedParser = (net.certware.evidence.hugin.ui.contentassist.antlr.internal.InternalNetDSLParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public NetDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(NetDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
