/**
 * generated by Xtext
 */
package net.certware.argument.sfp.validation;

import net.certware.argument.sfp.validation.AbstractSemiFormalProofValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class SemiFormalProofValidator extends AbstractSemiFormalProofValidator {
}
