/*
 * generated by Xtext
 */
package net.certware.intent.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import net.certware.intent.ui.internal.IntentSpecificationActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class IntentSpecificationExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return IntentSpecificationActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return IntentSpecificationActivator.getInstance().getInjector(IntentSpecificationActivator.NET_CERTWARE_INTENT_INTENTSPECIFICATION);
	}
	
}
