/**
 * generated by Xtext
 */
package net.certware.sacm.dsl.ui.contentassist;

import net.certware.sacm.dsl.ui.contentassist.AbstractSacmDslProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class SacmDslProposalProvider extends AbstractSacmDslProposalProvider {
}
