/**
 * generated by Xtext
 */
package net.certware.sacm.dsl.validation;

import net.certware.sacm.dsl.validation.AbstractSacmDslValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class SacmDslValidator extends AbstractSacmDslValidator {
}
