/*
 * generated by Xtext
 */
package net.certware.planning.cpn.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class CpnDslUiModule extends net.certware.planning.cpn.ui.AbstractCpnDslUiModule {
	public CpnDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
