/*
 * generated by Xtext
 */
package net.certware.argument.analysis.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import net.certware.argument.analysis.ui.internal.AnalysisDSLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AnalysisDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return AnalysisDSLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return AnalysisDSLActivator.getInstance().getInjector(AnalysisDSLActivator.NET_CERTWARE_ARGUMENT_ANALYSIS_ANALYSISDSL);
	}
	
}
