/*
 * generated by Xtext
 */
package net.certware.planning.cpn.ui.contentassist;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.ui.editor.contentassist.ContentAssistContext;
import org.eclipse.xtext.ui.editor.contentassist.ICompletionProposalAcceptor;

// import com.google.inject.Inject;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class CpnDslProposalProvider extends AbstractCpnDslProposalProvider {


	//@Inject
	//IScopeProvider provider;

	public void completePlan_Element(EObject model, Assignment assignment, ContentAssistContext context, ICompletionProposalAcceptor acceptor) {
		// original
		super.completePlan_Element(model, assignment, context, acceptor);
		lookupCrossReference(((CrossReference)assignment.getTerminal()), context, acceptor);
	}
}
