/**
 * generated by Xtext
 */
package net.certware.sacm.dsl.serializer;

import net.certware.sacm.dsl.serializer.AbstractSacmDslSyntacticSequencer;

@SuppressWarnings("all")
public class SacmDslSyntacticSequencer extends AbstractSacmDslSyntacticSequencer {
}
