/*
 * generated by Xtext
 */
package net.certware.argument.gsn.xdsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class GsnDslRuntimeModule extends net.certware.argument.gsn.xdsl.AbstractGsnDslRuntimeModule {

}
