/*
 * generated by Xtext
 */
package net.certware.argument.analysis.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import net.certware.argument.analysis.services.AnalysisDSLGrammarAccess;

public class AnalysisDSLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private AnalysisDSLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected net.certware.argument.analysis.parser.antlr.internal.InternalAnalysisDSLParser createParser(XtextTokenStream stream) {
		return new net.certware.argument.analysis.parser.antlr.internal.InternalAnalysisDSLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Output";
	}
	
	public AnalysisDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(AnalysisDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
