/*
 * generated by Xtext
 */
package net.certware.intent.state.ui.contentassist

import net.certware.intent.state.ui.contentassist.AbstractStateSpecificationProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class StateSpecificationProposalProvider extends AbstractStateSpecificationProposalProvider {
}
