/*
* generated by Xtext
*/
package net.certware.planning.cpn.ui.outline;

import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class CpnDslTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
